# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# For faster file watcher updates on Windows:
#gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw, :x64_mingw]

# Windows does not come with time zone data
#gem 'tzinfo-data', platforms: [:mswin, :mingw, :x64_mingw, :jruby]

# Include the tech docs gem
#gem 'govuk_tech_docs'

# Include the s3 gems to support deployment to AWS S3
#gem 'middleman-dotenv'
#gem 'middleman-s3_sync'
