# Host to use for canonical URL generation (without trailing slash)
host: sg-identity.gov.uk

# Header-related options
show_govuk_logo: true
service_name: sg-identity
service_link: https://www.sg-identity.gov.uk
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: /about/
  Documentation: /
  Support: /support/

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: false

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Redirects
#redirects:
#  /: /technical-documentation/

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 4

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

show_contribution_banner: true
github_repo: alphagov/YOUR_REPO
github_branch: main