@startuml Digital Identity Scotland System Context
top to bottom direction
hide stereotype
skinparam linetype polyline
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' Define user and RP above the DIS boundary
together {
  Person(user, "User", "Citizen wishing to access digital public services.")
  System_Ext(rp, "Relying Party", "Provider of digital public service.")
}
' Define the DIS boundary
together {
  System_Boundary(dis, "Digital Identity Scotland") {
      Container(ScotAccount, "ScotAccount", "Java", "Single Sign-On component for authentication and authorization")
      Container(mysafe, "MySafe", "Java", "Secure vault for storing user identity data and claims")
      Container(vyi, "VYI", "Java", "Verifies your identity through external identity verification services")
      ' MySafe roles and responsibilities
      note left of mysafe
        MySafe manages and shares users' personal information (user attributes) securely:
        1. Issuer Service/UI - Displays locker data, manages consent, and handles attribute requests.
        2. Locker Service - Ensures secure storage of user-selected attributes.
        3. Account Management Service/UI - Allows users to manage stored attributes and view sharing history.
        Users are directed to MySafe after authentication if relying parties request access to attributes 
        using specific scopes.
      end note
      ' ScotAccount roles and responsibilities
      note left of ScotAccount
        ScotAccount manages both authentication (Authn) and authorization (Authz):
        1. **Authn Responsibilities:**
          - Guides users through journeys: Sign Up, Sign In, Recover/Reset Email, 
            Reset Password, and Reset Phone Number.
          - Provides UI and backend API to manage journey sessions and user account records, 
            deployed as separate pods in a Kubernetes cluster.
        2. **Authz Responsibilities:**
          - Manages client registrations (relying parties) and handles OIDC user flows.
          - Acts as a wrapper around Connect2Id to customize its behavior and proxy its APIs.
          - Determines user destinations when the `/authorize` API is called:
              - Authn for authentication,
              - MySafe for consent,
              - Relying Party with an authorization code,
              - Error page for failures.
          - Primarily interacts with external parties but has internal interactions with 
            Authn, MySafe, and VYI.
      end note
      ' VYI roles and responsibilities
      note left of vyi
        VYI (Verify Your Identity) orchestrates third-party services to verify 
        a user's claimed identity according to GPG 45 at a medium level of assurance.
        **Responsibilities:**
        - Interacts with external verification providers (e.g., document checks, biometrics).
        - Ensures consistency with GPG 45 guidelines by verifying identity evidence, 
          corroboration, and validation processes. GPG 45 is a UK government guideline for identity verification.
        - Medium level of assurance requires:
          - Sufficient identity evidence (e.g., photo ID and address proof).
          - Verification of the claimed evidence's validity and accuracy.
          - Corroboration across multiple checks to ensure identity linkage.
      end note
  }
}
together {
  System_Boundary(experian_sb, "Experian") {
    ' Updated Experian services
    System_Ext(experian, "Experian Cross-Core Gateway", "Identity verification system delegating to multiple API services.") 
    System_Ext(idauth, "ID Authenticate", "Validates identity and assesses confidence levels.")
    System_Ext(hunter, "Hunter", "Fraud detection service analyzing user behavior.")
    System_Ext(mitek, "Mitek", "Biometric verification service for facial recognition.")
    System_Ext(iiq, "Experian Identity IQ", "Knowledge based verification. Challenge and response system.")
    System_Ext(wasp, "Experian WASP", "Authentication service. Issues security tokens to client to call other services e.g. Experian Identity IQ")
    ' Identity IQ roles and responsibilities
    note top of iiq
      1. Identity IQ performs challenge-response verification using trusted data.
      2. Asks randomly generated questions based on personal data only the legitimate user would know.
      3. Supports multiple clients and accounts with high configurability controlled by parameters.
    end note
    ' Wasp roles and responsibilities
    note top of wasp
      1. WASP secures access to Experian services such as Identity IQ.
      2. Authenticates clients using mTLS with an Experian provided certificate.
      3. After successful handshake issues limited life bearer token to be used in subsequent API reqests.
    end note
    ' ID Authenticate roles and responsibilities
    note bottom of idauth
      1. Validates name and address by searching trusted data sources.
      2. Checks for data inconsistencies indicating impersonation (e.g., mismatched DOB, deceased flags, credit activity).
      3. Assesses identity confidence based on number/quality of data proofs, duration, and type (e.g., mortgage vs credit card).
    end note
    ' Hunter roles and responsibilities
    note bottom of hunter
      Hunter screens applications and customers to highlight potentially fraudulent activity. 
      1. It checks against previous applications or accounts for potential data manipulation and anomalies that could indicate fraud
      2. Previous applications that are known or suspected to be fraudulent, indicators of fraud risk
      3. Identifies applications from individuals who are PEPs, subject to Sanctions, or with Adverse Media mentions that might indicate fraudulent activity.
    end note
    ' Mitek roles and responsibilities
    note bottom of mitek
      1. Verifies identity documents by analyzing security features.
      2. Performs facial comparison using a selfie and document photo to confirm ownership.
      3. Provides fraud indicators and checks against PEPs, sanctions, and media data.
    end note
  }
}
together {
  System_Ext(cifas, "Cifas", "Fraud identification system.")
  System_Ext(via, "Via Europa", "Address lookup system.")
  System_Ext(notify, "Gov.UK Notify", "Messaging system for SMS and email notifications.")
  System_Ext(mailbox, "Mailbox", "Digital mailbox service providing users with a secure mailbox to receive communication from public services in Scotland.")

  ' Gov.UK Notify roles and responsibilities
  note bottom of notify
    Gov.UK Notify is used to send notifications to users via SMS and email. 
    1. Provides notification during account registration, recovery, and verification processes.
    2. Sends secure one-time passwords (OTP).
  end note
  ' Cifas roles and responsibilities
  note bottom of cifas
    Cifas is used to enhance identity verification by checking for indications of risk or misuse 
    associated with a claimed identity. 
    1. Operates on a reciprocal basis, providing access to attempted/actual fraud details from other members.
    2. Requires submission of identified fraud cases and retention of records for 3-6 years.
    3. Supports more robust IDV checks and mitigates risks from knowledge-based verification.
  end note
  ' ViaEuropa roles and responsibilities
  note bottom of via
    ViaEuropa is used for address lookup services.
    1. Validates and standardizes user-provided addresses against authoritative address datasets.
    2. Ensures accurate and consistent address data for identity verification processes.
    3. Supports services that require precise address validation to mitigate input errors or fraud.
  end note
  ' Mailbox roles and responsibilities
   note bottom of mailbox
        Mailbox is a digital mailbox service that provides users with a secure mailbox to receive communication from public services in Scotland.
        1. It acts as a relying party for authentication and IDV.
        2. Undertakes a standard OIDC flow via ScotAccount.
        3. Provides a secure channel for users to receive important notifications and documents from public services.
        4. ScotAccount ensures that user has an associated mailbox after successfully going through IDV.         
  end note
}
' Relationships
user --> dis: "Authorization (account registration/idv, authentication, consent), account management, account recovery, logout, support request"
user -l-> rp: "Access protected resource"
rp --> dis: "Endpoint discovery, get keyset, get user data"
' Connections to external systems
dis --> experian: "Verify user identity biometrically."
dis --> wasp: "Authorize client and gather bearer token."
dis --> iiq: "Verify user identity via knowledge based challenge."
dis --> cifas: "Verify user fraud."
dis --> mailbox: "Authentication and verification of users triggering creation of mailbox."
dis --> via: "Lookup address."
dis --> notify: "Trigger SMS/Email."
notify -u-> user: "Send SMS/Email."
' Expanded Experian Cross-Core Gateway delegation
experian --> idauth: "Perform identity verification"
experian --> hunter: "Analyze user behavior for fraud"
experian --> mitek: "Use biometric verification for identity"
' Internal relationships within DIS
ScotAccount --> vyi: "Handles identity verification process"
vyi <--> mysafe: "Stores and retrieves identity data securely"
ScotAccount <--> mysafe: "Access user claims and attributes for authentication"
@enduml