@startuml Digital Identity Scotland System Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Citizen wishing to access to digital public services")

' External systems
System_Ext(rp, "Relying Party", "Provider of digital public service.")
System_Ext(experian, "Experian", "Identity checking system providing biometric and knowledge based verification.")
System_Ext(cifas, "Cifas", "Fraud identification system.")
System_Ext(via, "Via Europa", "Address lookup system.")
System_Ext(vouchsafe, "Vouchsafe", "Identity checking system providing a vouching mechanism.")
System_Ext(notify, "Gov.UK Notify", "Identity checking system providing a vouching mechanism.")

System_Boundary(dis, "Digital Identity Scotland") {
    Container(sso, "SSO", "Java", "")
    Container(mysafe, "MySafe","Java", "")
    Container(vyi, "VYI", "Java", "")
}

' Relationships
Rel(user, dis, "Authorization (account registration/idv, authentication, consent), account management, account recorvery, logout, support request")
Rel(user, rp, "Access protected resource")
Rel(rp, dis, "Endpoint discovery, get keyset, get user data")
Rel(dis, experian, "Verify user identity")
Rel(dis, cifas, "Verify user identity")
Rel(dis, vouchsafe, "Verify user identity")
Rel(dis, via, "Lookup address")
Rel(dis, notify, "Trigger SMS/Email")
Rel(notify, citizen, "Send SMS/Email")
Rel(vyi, sso, "")
BiRel(vyi, mysafe, "")
BiRel(sso, mysafe, "")

@enduml