@startuml vouchsafe-hld
' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v17.0/dist
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist
!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml

!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/EndUserComputing/all.puml
!include AWSPuml/General/all.puml
!include AWSPuml/Groups/all.puml
!include AWSPuml/NetworkingContentDelivery/all.puml
!include AWSPuml/Analytics/all.puml
!include AWSPuml/Storage/all.puml
!include AWSPuml/ApplicationIntegration/all.puml
!include AWSPuml/Compute/all.puml
!include AWSPuml/SecurityIdentityCompliance/all.puml
!include AWSPuml/Containers/all.puml

hide stereotype
skinparam linetype polyline

' External Service Icon for Identity IQ
together {
  Boundary(vouchsafe, "Vouchsafe") {
      rectangle "Vouchsafe API" as vouchsafeApi        
  }

  note bottom of vouchsafeApi #Beige
    **Vouchsafe API**:
    - Enables client to request a new verification, commencing a vouching process.
    - On commencement, vouchsafe provides a url to be used by client to redirect the user for verification
    - Client can track the progress of a verification journey synchronously via request/response API or asynchronously via a webhook API.
  end note

  note left of vouchsafeApi #Beige
    **Vouchsafe API**:
    - Client pre-authenticates with Vouchsafe using client id and secret to retrieve an access token.
    - All subsequent requests require use of access token.
    - Access token expires after 1 day. On expiry, access token needs refresh.
  end note

  note top of vouchsafeApi #Beige
    **Vouchsafe API**:
    - Vouchsafe acts as relying party for the referees journey
    - Undertakes a standard OIDC flow via ScotAccount
  end note
}


AWSCloudGroup(cloud) {
    AWSAccountGroup(build, "Digital_Identity-Production (Strategic Cloud Platform)") {
        Cluster_Boundary(eks, "EKS Cluster") {
            KubernetesPod(vyi, "VYI Service", "")
            KubernetesPod(mysafe, "MySafe Service", "")
            KubernetesPod(scotaccount, "ScotAccount", "") 
            
            note top of vyi #Beige
              **VYI Service**:
              - Verifies user's identity using external services from Vouchsafe.
              - Uses request/response API to receive notifications as a user moves through the stages of the vouching process
              - Ensures referees are biometrically verified
              - Communicates securely with Vouchsafe using **HTTPS/Rest** protocols.
            end note

            note top of mysafe #Beige
              **MySafe Service**:
              - Stores verified identity attributes.
              - Stores metadata about identity verification processes (e.g. KBV question quality).
            end note

            note top of scotaccount #Beige
              **ScotAccount Service**:
              - Authenticates and authorizes users and referees. 
              - Delegates to VYI for verification journey
              - Uses MySafe to retrieve verified claims
            end note
        }

        Cluster_Boundary(ecs, "ECS Cluster") {
            ElasticContainerService(squid, "Squid Proxy", "")

            note top of squid #Beige
              **Squid Proxy**:
              - Manages outbound internet traffic.
              - Allows access to Experian's Identity IQ and WASP API by whitelisting domains.
              - Ensures controlled and secure communication to external web services.
            end note
        }

        together {
            SimpleStorageServiceS3Standard(mysafeBucket, "MySafe S3 Bucket", "") #Transparent
            KeyManagementService(mysafeKey, "MySafe KMS Key", "") #Transparent

            note bottom of mysafeBucket #Beige
              **MySafe Bucket**:
              - Persists verified claims and metadata for verification processes.
              - Metadata includes quality of the KBV questions posed to users.
              - Encrypted at rest using KMS. 
              - Client side encrypted with segregation by account. 
            end note

            note bottom of mysafeKey #Beige
              **MySafe KMS Key**:
              - Provides encryption for the MySafe S3 bucket.
              - Key is managed for limiting access to MySafe service.
            end note
        }

        ' Add WAF and ALB for incoming traffic to ScotAccount
        WAF(waf, "AWS WAF", "")
        ElasticLoadBalancingApplicationLoadBalancer(alb, "Application Load Balancer", "")

        note top of waf #Beige
          **AWS WAF**:
          - Protects against common web exploits.
          - Filters incoming traffic to ScotAccount.
          - Allow lists traffic from the Vouchsafe API.
        end note

        note top of alb #Beige
          **Application Load Balancer**:
          - Distributes incoming traffic to ScotAccount.
          - Ensures high availability and fault tolerance.
          - Allow lists traffic from the Vouchsafe API.
        end note

        ' Connections for WAF and ALB
        vouchsafeApi --> waf : "HTTPS/Rest/JSON\nvia <&globe> Internet"
        waf --> alb : "HTTPS/Rest/JSON"
        alb --> scotaccount : "HTTPS/Rest/JSON\nvia Kubernetes Virtual Network"
    }
}

' Connections for internal services
vyi --> mysafe : "HTTP/REST/JSON\nvia Kubernetes Virtual Network"
scotaccount --> mysafe : "HTTP/REST/JSON\nvia Kubernetes Virtual Network"
scotaccount --> vyi : "HTTP/REST/JSON\nvia Kubernetes Virtual Network"

mysafe --> mysafeBucket : "HTTPS\nvia AWS network" 
mysafeBucket --> mysafeKey : "HTTPS\nvia AWS Network"

' VYI communicates with Squid Proxy
vyi --> squid : "HTTPS/Rest/JSON\nvia Squid Proxy"

' Squid Proxy communicates with the external Vouchsafe API
squid --> vouchsafeApi : "HTTPS/Rest/JSON\nvia <&globe> Internet"

@enduml