name: Generate Archdocs Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Adjust to your Ruby version
          bundler-cache: true
      - name: Build Middleman site
        run: |
          cd site 
          bundle exec middleman build --clean --verbose --build-dir=../site-build
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:   
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site-build
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          commit_message: 'Deploy Archdocs website'

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsS3DeployRole
#          aws-region: us-east-1 # Replace with your bucket’s region
#      - name: Deploy to S3
#        run: bundle exec middleman s3_sync
