name: Generate Archdocs Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Adjust to your Ruby version
          bundler-cache: true
      - name: Build Middleman site
        run: bundle exec middleman build --buiild-dir=site
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::123456789012:role/GitHubActionsS3DeployRole
#          aws-region: us-east-1 # Replace with your bucket’s region
#      - name: Deploy to S3
#        run: bundle exec middleman s3_sync
